CREATE TABLE ACCOUNT01(
	ACCDATE DATE,
	ACCUSE VARCHAR2(30),
	ACCCLASSIFY VARCHAR2(30),
	ACCMONEY NUMBER,
	ACCMEMO VARCHAR2(50) );

DROP TABLE ACCOUNT01;
SELECT * FROM ACCOUNT01;
SELECT * FROM ACCOUNT01 WHERE TO_CHAR(ACCDATE, 'YYMMDD') = '210221';
INSERT INTO ACCOUNT01 VALUES(SYSDATE, '식비', '지출', 12000, '점심식사');
DELETE FROM ACCOUNT01 WHERE ACCMEMO = '점심식사';

SELECT SUM(ACCMONEY) AS "EXPEND" FROM ACCOUNT01 WHERE ACCCLASSIFY IN '지출';
SELECT SUM(ACCMONEY) AS "INCOME" FROM ACCOUNT01 WHERE ACCCLASSIFY = '수입';

SELECT ACCCLASSIFY, SUM(b.ACCMONEY)
FROM ACCOUNT01 a, (SELECT * FROM ACCOUNT01 WHERE ACCCLASSIFY = '수입') b;  




