
CREATE TABLE USERTEST(
	ID VARCHAR2(30),
	NAME VARCHAR2(30),
	AGE NUMBER(3),
	JOINDATE DATE
);

SELECT * FROM USERTEST;

SELECT *
FROM (
	SELECT last_name, salary,
	    RANK()OVER(ORDER BY salary DESC) AS sa_rank
	FROM employees
)
WHERE sa_rank BETWEEN 10 AND 20;
